apiVersion: v1
kind: Template
labels:
  demo: coolstore-ui
metadata:
  annotations:
    description: CoolStore Web-UI buildconfigs template
    iconClass: icon-java
    tags: coolstore,webui,nodejs
  name: coolstore-ui-builds
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: web-ui
    labels:
      comp-required: "true"
      app: web-ui
  spec:
    tags:
    - name: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: web-ui
    labels:
      comp-required: "true"
      app: web-ui
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: web-ui:latest
    source:
      contextDir: coolstore-ui
      git:
        ref: master
        uri: https://github.com/RedHat-Middleware-Workshops/cloud-native-workshop-v2m4-labs
      type: Git
    strategy:
      sourceStrategy: 
        forcePull: false
        from:
          kind: ImageStreamTag
          name: nodejs:4
          namespace: openshift
      type: Source
    resources:
      limits:
        cpu: 500m
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "1Gi"

